
import React, { useState, useCallback } from 'react';
import { ApiEndpoint, SyncStatus } from './types';
import Sidebar from './components/Sidebar';
import Editor from './components/Editor';
import { generateEndpoint } from './services/geminiService';
import { pullFromGithub } from './services/githubService';

const App: React.FC = () => {
  const [endpoints, setEndpoints] = useState<ApiEndpoint[]>([]);
  const [selectedEndpointId, setSelectedEndpointId] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [syncStatus, setSyncStatus] = useState<SyncStatus>({ isSyncing: false });
  const [lastSynced, setLastSynced] = useState<number | undefined>(undefined);
  const [prompt, setPrompt] = useState('');

  const handleAddEndpoint = useCallback(async () => {
    if (!prompt.trim()) return;
    
    setIsGenerating(true);
    try {
      const result = await generateEndpoint(prompt);
      const newEndpoint: ApiEndpoint = {
        id: Math.random().toString(36).substr(2, 9),
        name: result.name || 'New Endpoint',
        method: (result.method as any) || 'GET',
        path: result.path || '/v1/new-endpoint',
        description: result.description || 'Generated by AI',
        responseSchema: result.responseSchema || '{}',
        exampleResponse: result.exampleResponse || {},
        createdAt: Date.now(),
      };
      
      setEndpoints(prev => [...prev, newEndpoint]);
      setSelectedEndpointId(newEndpoint.id);
      setPrompt('');
    } catch (error) {
      console.error('Generation failed:', error);
      alert('Failed to generate endpoint. Please check your prompt or API connectivity.');
    } finally {
      setIsGenerating(false);
    }
  }, [prompt]);

  const handlePullFromGithub = async () => {
    setSyncStatus({ isSyncing: true });
    try {
      const remoteEndpoints = await pullFromGithub('github.com/api-forge/main');
      setEndpoints(prev => {
        // Merge strategy: Add new endpoints, keep local ones
        const combined = [...prev];
        remoteEndpoints.forEach(remote => {
          if (!combined.find(c => c.path === remote.path && c.method === remote.method)) {
            combined.push(remote);
          }
        });
        return combined;
      });
      setLastSynced(Date.now());
      setSyncStatus({ isSyncing: false, lastAction: 'PULL' });
    } catch (err) {
      setSyncStatus({ isSyncing: false, error: 'Failed to pull from GitHub' });
    }
  };

  const handleUpdateEndpoint = (id: string, updates: Partial<ApiEndpoint>) => {
    setEndpoints(prev => prev.map(ep => ep.id === id ? { ...ep, ...updates } : ep));
  };

  const selectedEndpoint = endpoints.find(e => e.id === selectedEndpointId);

  return (
    <div className="flex h-screen w-full bg-slate-950 text-slate-200 overflow-hidden">
      <Sidebar 
        endpoints={endpoints} 
        selectedId={selectedEndpointId}
        onSelect={setSelectedEndpointId}
        onAdd={() => setSelectedEndpointId(null)}
        onPull={handlePullFromGithub}
        syncStatus={syncStatus}
        lastSynced={lastSynced}
      />
      
      <main className="flex-1 flex flex-col min-w-0">
        {!selectedEndpoint ? (
          <div className="flex-1 flex flex-col items-center justify-center p-8 text-center max-w-2xl mx-auto">
            <div className="w-20 h-20 bg-indigo-500/10 rounded-3xl flex items-center justify-center mb-8 border border-indigo-500/20 shadow-[0_0_50px_rgba(99,102,241,0.1)]">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 text-indigo-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            <h1 className="text-4xl font-bold text-white mb-4">What API shall we build?</h1>
            <p className="text-slate-400 text-lg mb-8 leading-relaxed">
              Describe the endpoint you need, or sync with GitHub to pull your existing repository schemas.
            </p>
            
            <div className="w-full relative group">
              <input
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleAddEndpoint()}
                placeholder="Type your API requirement..."
                disabled={isGenerating}
                className="w-full bg-slate-900 border-2 border-slate-800 focus:border-indigo-500 text-white rounded-2xl px-6 py-4 outline-none transition-all shadow-xl group-hover:border-slate-700 disabled:opacity-50"
              />
              <button
                onClick={handleAddEndpoint}
                disabled={isGenerating || !prompt.trim()}
                className="absolute right-3 top-3 bottom-3 px-6 bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-700 text-white rounded-xl font-semibold transition-all flex items-center gap-2"
              >
                {isGenerating ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                    Forging...
                  </>
                ) : (
                  <>
                    <span>Generate</span>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" />
                    </svg>
                  </>
                )}
              </button>
            </div>
            
            <div className="mt-12 grid grid-cols-2 gap-4 w-full text-left">
              {[
                "E-commerce product list with filters",
                "Weather forecast with hourly breakdown",
                "Crypto wallet balance tracker",
                "Task manager with nested subtasks"
              ].map((hint) => (
                <button
                  key={hint}
                  onClick={() => setPrompt(hint)}
                  className="p-3 text-xs bg-slate-900 border border-slate-800 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-all truncate"
                >
                  " {hint} "
                </button>
              ))}
            </div>
          </div>
        ) : (
          <Editor 
            endpoint={selectedEndpoint} 
            onUpdate={handleUpdateEndpoint}
          />
        )}
      </main>

      {/* Global Header */}
      <div className="fixed top-0 right-0 p-4 pointer-events-none flex items-center gap-3">
         <div className="px-3 py-1 bg-slate-900/80 backdrop-blur-md border border-slate-800 rounded-full flex items-center gap-2 pointer-events-auto">
           <div className={`w-2 h-2 rounded-full ${syncStatus.isSyncing ? 'bg-amber-500 animate-spin' : 'bg-emerald-500 animate-pulse'}`}></div>
           <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">
             {syncStatus.isSyncing ? 'Syncing Repository...' : 'AI Engine Online'}
           </span>
         </div>
      </div>
    </div>
  );
};

export default App;
